### PR TITLE
Larbi's changes

### PR DESCRIPTION
**Pull request by semekork**
You have to update this Larbi
Looks like you have left it unattended for a really longtime

### CODE REVIEW

**Comment by semekork** [comment]
Guys I know this isn't the right place to write this piece of sh*t 
but I got to
Because it looks like we are not really focusing on this project.
It can take as 10 years to finish this IF we aren't serious about it
BUT
It can take us less then 4 months to complete this if we are determined

**Comment by Me45y63** [comment]
Yeah you're right

**Comment by Me45y63** [comment]
@semekork there are some major conflicts so I can't accept this merge. He has to review the conflicts and make the necessary changes himself. I suggested some videos to him as well. About the projects, we will continue initially this shouldn't have taken a very long time. Send me the changes you have so far and let me start linking everything together.

**Comment by semekork** [comment]
> @semekork there are some major conflicts so I can't accept this merge. He has to review the conflicts and make the necessary changes himself. I suggested some videos to him as well. About the projects, we will continue initially this shouldn't have taken a very long time. Send me the changes you have so far and let me start linking everything together.

**Pull request closed without merging**
